### ISSUE TITLE
Bug when chaining on a partially-applied function

### ISSUE THREAD

**Issue by vendethiel** [gkz/LiveScript#1042]
```
$ bin/lsc -bce 'Object.keys _ .length'
TypeError: Cannot read property 'length' of undefined
    at ctor$.exports.Chain.Chain.add (~/LiveScript/lib/ast.js:1046:111)
    at Object.anonymous (~/LiveScript/lib/parser.js:96:41)
    at Parser.parse (~/LiveScript/lib/parser.js:912:36)
    at Object.exports.compile (~/LiveScript/lib/index.js:45:20)
    at compileScript (~/LiveScript/lib/command.js:202:29)
    at ~/LiveScript/lib/command.js:80:9
    at Object.<anonymous> (~/LiveScript/bin/lsc:7:26)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

**Comment by rhendric** [comment]
#746 dupe?

**Comment by vendethiel** [comment]
Indeed, I had no recollection of this. I'll move the discussion there :-).
