### ISSUE TITLE
Will LiveScript support Probabilistic Programming?

### ISSUE THREAD

**Issue by wuxianliang** [gkz/LiveScript#699]
Dear Friends:
LiveScript is beautiful. Recently a new probabilistic programming, Webppl, http://webppl.org/ http://dippl.org/ publishes on npm. It is functional, embeded in JavaScript, and ugly.

Can LiveScript be beautiful and supporting a small probabilistic programming subset?

It sounds non sense. Anyway, today is Apr 1st and we all dream something different.

**Comment by vendethiel** [comment]
It seems those are just NPM modules, right? You can use them from LS.

**Comment by wuxianliang** [comment]
Dear @vendethiel 
May I ask how? Thank you very much!
I have a try.

This is a small .wppl
```javascript
  var geometric = function(p) {
    return flip(p) ? 1 + geometric(p) : 1;
   };
   
   Enumerate(
       function() {return geometric(0.5);},
       10);
             
```
we compile them as .js  to .ls
```livescript
geometric = (p) -> if flip p then 1 + geometric p else 1

Enumerate (-> geometric 0.5), 10
```
How great it looks!
But when we compile this .ls to .js, the result can not run as .wppl.

And  how to compile .ls to .js as Webppl does? 
After 
```
webppl examples/geometric.wppl --compile --out geometric.js
```
we receive 
```javascript
var webppl = require('/usr/local/lib/node_modules/webppl/src/main.js');
function isErp(x) {
  return (x && (x.score != undefined) && (x.sample != undefined));
}
function isErpWithSupport(x) {
  return (isErp(x) && (x.support != undefined));
}
function printWebPPLValue(x) {
  if (isErpWithSupport(x)) {
    console.log('ERP:');
    var erpValues = x.support([])
        .map(function(v) {return [JSON.stringify(v), Math.exp(x.score([], v))]})
        .sort(function(a, b) {return b[1] - a[1]});
    erpValues.forEach(function(val) {console.log('    ' + val[0] + ': ' + val[1]);});
  } else {
    console.log(x);
  }
}
var topK = function(s, x){ 
 console.log('\n* Program return value:\n'); 
 printWebPPLValue(x); 
};

var main = (function (p) {
    return function (s, k, a) {
        var trampoline = p(s, k, a);
        while (trampoline) {
            trampoline = trampoline();
        }
    };
}(function (globalStore, _k0, _address0) {
    var flip = function flip(globalStore, _k181, _address1, theta) {
        return function () {
            return sample(globalStore, _k181, _address1.concat('_0'), bernoulliERP, [theta]);
        };
    };
    var geometric = function geometric(globalStore, _k2, _address104, p) {
        return function () {
            return flip(globalStore, function (globalStore, _result3) {
                return function () {
                    return _result3 ? geometric(globalStore, function (globalStore, _result4) {
                        return function () {
                            return _k2(globalStore, 1 + _result4);
                        };
                    }, _address104.concat('_106'), p) : _k2(globalStore, 1);
                };
            }, _address104.concat('_105'), p);
        };
    };
    return function () {
        return Enumerate(globalStore, _k0, _address0.concat('_108'), function (globalStore, _k1, _address105) {
            return function () {
                return geometric(globalStore, _k1, _address105.concat('_107'), 0.5);
            };
        }, 10);
    };
}));

main({}, topK, '');
```

**Comment by vendethiel** [comment]
> But when we compile this .ls to .js, the result can not run as .wppl.

I don't get this part. why not?

**Comment by wuxianliang** [comment]
Sorry, I do know why. these are the codes.

```livescript
 geometric = (p) -> if flip p then 1 + geometric p else 1
```
the complied javascript is 
```javascript
   // Generated by LiveScript 1.3.1
  //(function(){
     var geometric;
     geometric = function(p){
       if (flip(p)) {
         return 1 + geometric(p);
       } else {
         return 1;
       }
    };
  //}).call(this);
```
report error
```
Processing geometri.wppl

/usr/local/lib/node_modules/webppl/src/transforms/cps.js:165
  switch (node.type) {
              ^
TypeError: Cannot read property 'type' of null
    at cps (/usr/local/lib/node_modules/webppl/src/transforms/cps.js:165:15)
    at /usr/local/lib/node_modules/webppl/src/transforms/cps.js:225:14
    at /usr/local/lib/node_modules/webppl/src/syntax.js:30:27
    at cpsDeclarations (/usr/local/lib/node_modules/webppl/src/transforms/cps.js:230:5)
    at Array.<anonymous> (/usr/local/lib/node_modules/webppl/src/transforms/cps.js:275:14)
    at Array.5 (/usr/local/lib/node_modules/webppl/src/syntax.js:30:27)
    at loop (/usr/local/lib/node_modules/webppl/src/syntax.js:45:27)
    at /usr/local/lib/node_modules/webppl/src/syntax.js:46:14
    at Array.4 (/usr/local/lib/node_modules/webppl/src/syntax.js:34:19)
    at loop (/usr/local/lib/node_modules/webppl/src/syntax.js:45:27)
```

**Comment by vendethiel** [comment]
Seems like you should report a bug there :)

**Comment by wuxianliang** [comment]
It is not a bug I think.There is a rule in .wppl "Note that there are no AssignmentExpressions or looping constructs (e.g., for, while, do). This is because a purely functional language is much easier to transform into Continuation Passing Style (CPS), ......"

When I remove 
```javascript
var geometric;
```
it works!

So is there a convenient way to avoid "var geometric;"?

**Comment by wuxianliang** [comment]
@vendethiel  would you like to add a new feature, something like
```shell
lsc -c2wppl subset.ls subset.wppl
```
There are rarely people using it, but it is opening a new direction. Thank you. :)

**Comment by vendethiel** [comment]
no, I don't think it's worth it. It's a bug in wppl, and it should be fixed.
