### ISSUE TITLE
lsc is not opening repl

### ISSUE THREAD

**Issue by Announcement** [gkz/LiveScript#897]
on Windows 7 powershell (haven't tested any other environment yet with livescript 1.5.0) simply typing `lsc` isn't opening a repl.

anyone experiencing the same issue or know what that's about?

**Comment by dk00** [comment]
if it said `TypeError: Path must be a string. Received undefined`
add environment variable 'HOME' with value %USERPROFILE% and it should open.

https://github.com/gkz/LiveScript/pull/695/commits/b32276a07f8fda41b0ee0f8ee75bccf2d549349e#diff-62cab7f67fcaea6ddbe4abb9d1d32828R254
Windows does not have 'HOME', 'HOMEPATH' should be used instead

**Comment by atifaziz** [comment]
> anyone experiencing the same issue or know what that's about?

Yes, with 1.5, I'm seeing the same.

```
B:\>npm i livescript
livescript@1.5.0 node_modules\livescript
├── prelude-ls@1.1.2
├── source-map@0.5.6
└── optionator@0.8.1 (fast-levenshtein@1.1.4, type-check@0.3.2, deep-is@0.1.3, wordwrap@1.0.0, levn@0.3.0)

B:\>node_modules\.bin\lsc.cmd
LiveScript 1.5.0 - use 'lsc --help' for more information
path.js:233
      throw new TypeError('Arguments to path.join must be strings');
            ^
TypeError: Arguments to path.join must be strings
    at Object.win32.join (path.js:233:13)
    at repl (B:\node_modules\livescript\lib\command.js:394:24)
    at B:\node_modules\livescript\lib\command.js:131:7
    at Object.<anonymous> (B:\node_modules\livescript\bin\lsc:7:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

But using 1.4, I get the REPL with the same steps:

```
B:\>npm i livescript@1.4.0
livescript@1.4.0 node_modules\livescript
├── prelude-ls@1.1.2
├── optionator@0.6.0 (fast-levenshtein@1.0.7, deep-is@0.1.3, type-check@0.3.2, levn@0.2.5, wordwrap@0.0.3)
└── source-map@0.3.0 (amdefine@1.0.0)

B:\>node_modules\.bin\lsc.cmd
LiveScript 1.4.0 - use 'lsc --help' for more information
ls>
```

This was from a standard Command Prompt and not using PowerShell.

**Comment by gkovacs** [comment]
This error is still occurring in Livescript 1.5.0 on Windows 10. The new error message is:

```
PS C:\Users\geza> lsc
LiveScript 1.5.0 - use 'lsc --help' for more information
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at repl (C:\Users\geza\AppData\Roaming\npm\node_modules\livescript\lib\command.js:394:24)
    at C:\Users\geza\AppData\Roaming\npm\node_modules\livescript\lib\command.js:131:7
    at Object.<anonymous> (C:\Users\geza\AppData\Roaming\npm\node_modules\livescript\bin\lsc:7:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by rhendric** [comment]
Hey, I don't have access to a Windows box right now; could someone on this thread provide independent confirmation that #1066 results in a working REPL on Windows?
