### ISSUE TITLE
Livescript 1.5.0 REPL: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by aafrey** [gkz/LiveScript#908]
I'm having issues with the REPL on Windows 7. This seems to be 1.5.0 specific as 1.3.0 works fine.
Full error output below.
```
LiveScript 1.5.0 - use 'lsc --help' for more information
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at repl (C:\Users\afrey\AppData\Roaming\npm\node_modules\livescript\lib\command.js:394:24)
    at C:\Users\afrey\AppData\Roaming\npm\node_modules\livescript\lib\command.js:131:7
    at Object.<anonymous> (C:\Users\afrey\AppData\Roaming\npm\node_modules\livescript\bin\lsc:7:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by aafrey** [comment]
I did not see this had already been solved.

https://github.com/gkz/LiveScript/issues/897
