### ISSUE TITLE
CLI (v1.5.0) in watch mode crashes on file save

### ISSUE THREAD

**Issue by mt0erfztxt** [gkz/LiveScript#909]
Node version is 5.5.0.

When saving file with following content:
```livescript
describe "Some", ->
  describe "thing", (...) ->
    it"should do something", (done) ->
      done!
```
CLI v1.5.0 crashes with following error:
```text
LiveScript version 1.5.0
Failed at: src/code.test.js.ls
/home/mt0erfztxt/Projects/Issues/example-of-lsc-crash/node_modules/livescript/lib/command.js:260
            warn(e + '\x07');
                   ^

TypeError: Function.prototype.toString is not generic
    at Function.toString (native)
    at compileScript (/home/mt0erfztxt/Projects/Issues/example-of-lsc-crash/node_modules/livescript/lib/command.js:260:20)
    at /home/mt0erfztxt/Projects/Issues/example-of-lsc-crash/node_modules/livescript/lib/command.js:152:11
    at /home/mt0erfztxt/Projects/Issues/example-of-lsc-crash/node_modules/livescript/lib/command.js:142:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```
CLI v1.4.0 just [reports](https://github.com/mt0erfztxt/example-of-lsc-crash/blob/master/lsc%20crash%20report.txt#L14) compile error and waits for changes. Same error but for another case is mentioned in #900.
Repo to reproduce error is [here](https://github.com/mt0erfztxt/example-of-lsc-crash), emit `npm run watch` to see it in action.

**Comment by mt0erfztxt** [comment]
After looking again it seems like this is a duplicate of #900.
If some one needs to workaround this issue until fix would published one of posible solutions can be found on [SO](http://stackoverflow.com/questions/696839/how-do-i-write-a-bash-script-to-restart-a-process-if-it-dies).
