### ISSUE TITLE
Bug: Wrong function argument interpretation, passed int, prelude-ls method expected function

### ISSUE THREAD

**Issue by IgorMuzyka** [gkz/LiveScript#919]
livescript: 1.5.0
prelude-ls: 1.1.2

Code:
```livescript
{take, drop} = require "prelude-ls"

array = [1 to 16]

chopListBy = (list, chopBy) ~>
	sublists = []

	while list.length > 0
		sublist = take chopBy list
		sublists.push sublist
		list = drop chopBy list

	sublists


a = chopListBy array, 5
```

Error:
```
$ lsc ./test.ls 
Failed at: ./test.ls
TypeError: chopBy is not a function
    at chopListBy (/****/test.ls:9:20)
 5| chopListBy = function(list, chopBy){
 6|   var sublists, sublist;
 7|   sublists = [];
 8|   while (list.length > 0) {
 9+     sublist = take(chopBy(list));
10|     sublists.push(sublist);
11|     list = drop(chopBy(list));
12|   }
13|   return sublists;
    at Object.<anonymous> (/*****/test.ls:15:5)
11|     list = drop(chopBy(list));
12|   }
13|   return sublists;
14| };
15+ a = chopListBy(array, 5);
16| console.log(a);
17| 
18| 
19| 
    at Module._compile (module.js:541:32)
    at Object.LiveScript.run (/usr/local/lib/node_modules/livescript/lib/node.js:31:19)
    at compileScript (/usr/local/lib/node_modules/livescript/lib/command.js:222:31)
    at /usr/local/lib/node_modules/livescript/lib/command.js:152:11
    at /usr/local/lib/node_modules/livescript/lib/command.js:142:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**Comment by IgorMuzyka** [comment]
Sorry me for being stupid missed commas when passing `chopBy` to take and drop
