### ISSUE TITLE
Corner case where "it" keyword is not detected

### ISSUE THREAD

**Issue by corwin-of-amber** [gkz/LiveScript#954]
With newest stable version (1.5.0):
```livescript
ls> f = -> {it.x}
[Function: f]
ls> f({x:7})
ReferenceError: it is not defined
    at f (repl:5:8)
    at repl:3:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at Interface.<anonymous> (/opt/local/lib/node_modules/livescript/lib/command.js:514:18)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:239:10)
    at Interface._line (readline.js:583:8)
```

It seems that the compiler is generating a function with no arguments:
```javascript
% echo "-> {it.x}" | lsc -c
// Generated by LiveScript 1.5.0
(function(){
  (function(){
    return {
      x: it.x
    };
  });
}).call(this);
```

**Comment by rhendric** [comment]
Duplicate of #899 and #951. This is fixed but not released.

**Comment by corwin-of-amber** [comment]
Oh yeah I was searching through existing open issues but not closed ones!
